critic:
  q0: -10.
  gamma: 0.99
  strategy: oracle
  lr:
    id: LinearDecay
    init_value: 1.0
    min_value: 1.0
    decay: null
    steps: null
    warmup: 0

actor:
  eps:
    id: LinearDecay
    init_value: 1.0
    min_value: 0.0
    decay: null
    steps: ${experiment.training_steps}
    warmup: 0
